name: Publish Container
on:
  push:
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_LATEST: ghcr.io/${{ github.repository }}:latest
  IMAGE_VERSION: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -t "${{ env.IMAGE_LATEST }}" -t "${{ env.IMAGE_VERSION }}" .
      - run: docker image push "${{ env.IMAGE_LATEST }}"
      - run: docker image push "${{ env.IMAGE_VERSION }}"
